#!/bin/bash

#
# /etc/rc
# This script is executed at boot by rc.service systemd service
# 

rfkill block bluetooth # disable bluetooth at boot
echo "powersave" > /sys/module/pcie_aspm/parameters/policy # enable powersupersave ASPM policy 
